version: '3.3'

services:
  namenode:
    image: bde2020/hadoop-namenode:3.3.3-java8
    hostname: "namenode-{{.Node.ID}}"
    networks:
      - hadoop
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - /data/container_data/namenode:/hadoop/dfs/name
      - /tmp:/tmp
    environment:
      - CLUSTER_NAME=HADOOP
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.namenode==true
      restart_policy:
        condition: on-failure

  datanode:
    image: bde2020/hadoop-datanode:3.3.3-java8
    hostname: "datanode-{{.Node.ID}}"
    networks:
      - hadoop
    volumes:
      - /data/container_data/datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    ports:
     - target: 9864
       published: 9864
       mode: host
     - target: 9866
       published: 9866
       mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.datanode==true
      restart_policy:
        condition: on-failure

  nodemanager:
    image: bde2020/hadoop-nodemanager:3.3.3-java8
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.datanode==true
      restart_policy:
        condition: on-failure

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:3.3.3-java8
    networks:
      - hadoop
    ports:
     - 18088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9870 historyserver:8188"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.namenode==true
      restart_policy:
        condition: on-failure

  historyserver:
    image: bde2020/hadoop-historyserver:3.3.3-java8
    networks:
      - hadoop
    ports:
      - 18188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    volumes:
      - /data/container_data/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.namenode==true
      restart_policy:
        condition: on-failure

  metastore:
    image: postgres:latest
    networks:
      - hadoop
    volumes:
      - /data/container_data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: "hive"
      POSTGRES_USER: "hive"
      POSTGRES_DB: "hive"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.namenode==true
      restart_policy:
        condition: on-failure

  hiveserver:
    image: bde2020/hadoop-hiveserver:3.3.3-java8
    networks:
      - hadoop
    ports:
      - 20000:10000
      - 20002:10002
    environment:
      SERVICE_PRECONDITION: "namenode:9870 metastore:5432 resourcemanager:8088 historyserver:8188"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.namenode==true
      restart_policy:
        condition: on-failure

networks:
  hadoop:
